version: '3.3'
services:
    node:
        container_name: project-api-music-share
        image: 'node:latest'
        working_dir: /home/node/app/backend
        env_file:
            - .env
        command:
            - /bin/sh
            - '-c'
            - 'npm install && npm start'
        ports:
            - '3000:3000'
        volumes:
            - './backend:/home/node/app/backend'
        links:
            - mongo
    mongo:
        container_name: project-api-mongo
        image: 'mongo:latest'
        ports:
            - '27017:27017'
        volumes:
            - 'mongo-data:/data/db'

volumes:
    mongo-data:
